### ISSUE TITLE
Add Integration Test

### ISSUE THREAD

**Issue by jul-sh** [project-oak/transparent-release#13]
@rbehjati pointed out in https://github.com/project-oak/transparent-release/pull/9#issuecomment-1028798921 that it would be good to have more tests. 

We currently have a fair amount of snapshot tests and unit tests and snapshot tests for individual pieces of code, such as [sha256 hashing](https://github.com/project-oak/transparent-release/blob/b5c32a38184c44821e2d5abe71022e5fcf2b2ba5/common/common_test.go#L27) or the parsing of a [given config file](https://github.com/project-oak/transparent-release/blob/b5c32a38184c44821e2d5abe71022e5fcf2b2ba5/common/common_test.go#L66).

I think it would be good to add an integration test that tests the functionality of our tooling. That is parsing a provenance file, running a build, and verifying the hash. This would be helpful as it tests the functionality of code, as opposed to its specific implementation. 

An advantage of integration tests is that they test a lot of code at once. This is a good fit here, as the codebase is relatively small and hence straightforward to debug.

**Comment by rbehjati** [comment]
> I think it would be good to add an integration test that tests the functionality of our tooling. That is parsing a provenance file, running a build, and verifying the hash.

The test added in #12 implements exactly that scenario. 

Do you think we also need a separate test for the command line in `cmd/build`?

**Comment by jul-sh** [comment]
@rbehjati Nice! That's good. I left a comment on the PR. At the moment #12 tests pretty much just that verify function does not error. I think it would make for a more meaningful test if it could check that a build was actually performed and did yield the expected hash. 

> Do you think we also need a separate test for the command line in cmd/build?
I think it would be nice, yes. :) 

A full end to end test would cover that (aka one that invokes the CLI on the command line and verifies it's output). It would require some extra testing setup outside of bazel however.

**Comment by rbehjati** [comment]
> At the moment https://github.com/project-oak/transparent-release/pull/12 tests pretty much just that verify function does not error.

That is a good point. Yes. Let's add a more fine-grained test, in addition to the one in #12.

**Comment by jul-sh** [comment]
I have wrote one, but I'm a bit hesitant for submitting changes at this point

**Comment by rbehjati** [comment]
> I have wrote one, but I'm a bit hesitant of submitting changes at this point

Why?
