### ISSUE TITLE
Issuer, signer, or both in the claim format?

### ISSUE THREAD

**Issue by rbehjati** [project-oak/transparent-release#134]
The current design of the [claim format](https://github.com/project-oak/transparent-release/blob/50e7f8b68a58eb4f112790701570eab42199d6dc/docs/claim-transparency.md#the-claim-format) allows specifying an **issuer**. Currently we require the issuer to be the same as the signer. This brings a few questions and issues (see https://github.com/project-oak/transparent-release/pull/130#discussion_r978672866).

To fix this we have two options:
- Remove the issuer:
    - Rationale: if the issuer and the signer are always the same, having a separate field for the issuer is redundant. 
    - Does this design have any security drawbacks?
- Keep the issuer and make sure it is consistent with the signer 
    - In this case, to make sure the issuer and the singer match, the tool that generates the claim and fills out the issuer must also sign the claim. 
    - Currently the only tool that generates a claim is our endorser. Adding signing functionality to it can be complicated. Particularly, given that we will most likely need to support different signing technologies (e.g., on GitHub and GCB).
    - How is a signer identified? In our current design the issuer has an ID which is a URI. With both a signer and an issuer, how do we map the signer (often identified by its public key) to the URI representing the issuer? This is important when verifying the claims.

Note that in the [SLSA provenance format](https://slsa.dev/provenance/v0.2) the **builder** (which is a concept similar to issuer in our current design) is different from the signer. However, SLSA provenance specification states that: 
> “Consumers MUST accept only specific (signer, builder) pairs. For example, “GitHub” can sign provenance for the “GitHub Actions” builder, and “Google” can sign provenance for the “Google Cloud Build” builder, but “GitHub” cannot sign for the “Google Cloud Build” builder."

I think it is best to remove the issuer. In future, if we see a need for it, we can add it to the spec. 
What do you think @tiziano88, @mariaschett?

**Comment by tiziano88** [comment]
Yes I agree we should remove the issuer; what counts is who / what actually signs a claim; in fact, the same claim may be signed by multiple parties (e.g. if they all want to endorse a binary for the same claim), so there would not be a single issuer (and not even a single signer, of course).

In fact, as you noted, having an issuer separate from the signer may actually lead to security problems, in which the correspondence between the two is not correctly validated by consumers of the claim. And if the validation is expected to be that they must match exactly (whatever that means), then keeping them as separate fields still adds no value.

IIUC then the signer would just be implicitly identified by its public key, right? So a consumer of a claim would have a list of public keys that it trusts. How those map to actual entities is out of scope, though we should think through a few examples to make sure it works for our practical use cases (e.g. Oak team signing something -- how is the Oak team identified?).

**Comment by mariaschett** [comment]
I don't see any reason for keeping the issuer, so happy to go with your suggestion @rbehjati .

**Comment by rbehjati** [comment]
Thanks for the responses. Then I'll remove the issuer. 

> in fact, the same claim may be signed by multiple parties (e.g. if they all want to endorse a binary for the same claim), so there would not be a single issuer (and not even a single signer, of course).

Exactly. 

> IIUC then the signer would just be implicitly identified by its public key, right?

It is true. 

> So a consumer of a claim would have a list of public keys that it trusts. How those map to actual entities is out of scope, though we should think through a few examples to make sure it works for our practical use cases (e.g. Oak team signing something -- how is the Oak team identified?).

I agree. The Oak team just needs to somehow publish its public key.
