### ISSUE TITLE
Add library for generating endorsements

### ISSUE THREAD

**Issue by rbehjati** [project-oak/transparent-release#141]
We need an endorser tool to generate an endorsement statement for a given binary. The tool should take as input one or more provenances, and verify them before generating the endorsement statement.

**Comment by rbehjati** [comment]
The provenances that are verified as part of the process will be referenced as evidence in the endorsement statement, and for that we need to specify each provenance with a URI. I wonder what is a sensible choice for the URI. The other thing to consider is the format of the provenance. 

Here are some options for the provenance format and the choice of the URI:

- Rekor LogEntry wrapping the provenance as a base64-encoded string, and URL for fetching the LogEntry from Rekor as the URI ([example](https://rekor.sigstore.dev/api/v1/log/entries/24296fb24b8ad77a872690e11780e927d9eddd1bc3a598e5490ad1c75fe039289a5dccc5b4d71576)). 
- Provenance as a DSSE document generated on GitHub using the SLSA generic GitHub generator (See [example job](https://github.com/project-oak/oak/actions/runs/3245675958) with the DSSE document uploaded as an artefact) with the URI same as above.
  - In this case the URI still retrieves the LogEntry, and we have no way of retrieving the DSSE document. But both contain the same provenance.
  - The artefacts uploaded to GitHub will be removed automatically after a month or so. So we cannot use the GitHub link as URI.
  - The [slsa-verifier](https://github.com/slsa-framework/slsa-verifier/blob/3ab86db54772c8191cfeca9a307495a5529e23fd/README.md#verification-for-github-builders) also takes DSSE documents as input. The benefit of this option is that it will allow us to reuse the slsa-verifier with minimal modification.
- Provenance and signature (detached or as a DSSE document), uploaded to a separate storage such as ent, plus the URL of the storage as the URI. 
  - This gives us more control, and if we use the DSSE document as the format then we will still be able to reuse a lot of the verification functionality from the slsa-verifier. 

Also, I think we'd want to verify that the provenance and the URI match. So, a better design should only get as input either the URI and use it to fetch the actual provenance, or get the provenance and somehow find the correct URI for it. In particular, for the latter, it should be possible to find the Rekor LogEntry for a valid signed provenance. 

What do you think @tiziano88 and @mariaschett?

**Comment by tiziano88** [comment]
In general we should address everything by content (i.e. by digest), so my preference is the third option you presented. In fact in https://github.com/project-oak/oak/pull/3314#discussion_r995624992 I also suggested that we should upload the provenance and also any related signatures and inclusion proofs to Ent, so that we can then later reference them from there, without depending on rekor or GitHub artifacts to be around in the future.
Just to confirm though, it should be possible to upload the DSSE document, like in the second option, right? Basically only use Ent instead of GitHub artifacts, but otherwise leave everything else the same. Would that work?

**Comment by rbehjati** [comment]
An endorser command line tool is also added in https://github.com/project-oak/transparent-release/pull/240.
