### ISSUE TITLE
Consider using protobuf instead of json schema

### ISSUE THREAD

**Issue by rbehjati** [project-oak/transparent-release#15]

**Comment by jul-sh** [comment]
**Pros**
proto has a robust ecosystem for parsing messages into different programming languages. with TOML / JSON schemas we usually have to write our own go structs to parse them. In essence that means duplicating the structure. If you update the schema, you need to update the go structs too. Tools for generating either off the other exist, but ime are not very mature. Protobuf is more mature. 

**Cons**
- Quite Google specific, this would likely make our tooling less appealing to people not familiar with protobuf. 
- SLSA and in-toto both require JSON. 

**Questions**
Protobuf is usually used to encoding messages. Is there a standard to write messages to a file? Does it keep them human readable?

**Comment by jul-sh** [comment]
Overall I think at the moment the cost of needing to maintain both a schema and go structs is manageable, esp with tests.

**Comment by rbehjati** [comment]
Thanks for the elaborate description. I agree that json schema is a suitable choice for now. Closing this issue, but we can continue the discussion, and reopen it if needed.
