### ISSUE TITLE
Generalize `endorser` to work on `ProvenanceIR`

### ISSUE THREAD

**Issue by mariaschett** [project-oak/transparent-release#165]
Based on this [comment](https://github.com/project-oak/transparent-release/pull/164/files#r1046043774) we want the `endorser` to not depend on the provenance format--either SLSA or Amber---but on `ProvenanceIR`.

**Comment by mariaschett** [comment]
Two questions, @rbehjati :

1. When verifying consistency of provenances, we rely on a `BinaryName`. Is a BinaryName always present, similar to the binary digest? Or only for some buildTypes?

2. When generalizing the endorser to work on `ProvenanceIR`: where do we want to make the decision on the buildType? I propose to either (a) change the interface of `GenerateEndorsement` to take an argument `toProvenanceIR func([]byte) (*common.ProvenanceIR, error)` similar to [here](https://github.com/project-oak/transparent-release/blob/4c7ee505df1d92f34f4069a7f401cc11530498dc/internal/endorser/endorser.go#L51). Alternatively, we could (b) give the `buildType` as argument to `GenerateEndorsement`. What do you think?

**Comment by rbehjati** [comment]
> 1. When verifying consistency of provenances, we rely on a `BinaryName`. Is a BinaryName always present, similar to the binary digest? Or only for some buildTypes?

It is always present. But I don't think we need a reference value for it. If there are multiple input provenances, all must agree on the `BinaryName`. The `BinaryName` is copied to the endorsement. 

> 2. When generalizing the endorser to work on `ProvenanceIR`: where do we want to make the decision on the buildType? I propose to either (a) change the interface of `GenerateEndorsement` to take an argument `toProvenanceIR func([]byte) (*common.ProvenanceIR, error)` similar to [here](https://github.com/project-oak/transparent-release/blob/4c7ee505df1d92f34f4069a7f401cc11530498dc/internal/endorser/endorser.go#L51). Alternatively, we could (b) give the `buildType` as argument to `GenerateEndorsement`. What do you think?

I don't think any of this is needed. The `buildType` is already part of the provenance. So no additional parameter is needed for deciding which `buildType` to use.

At a high-level I can imaging a function `FromProvenance` similar to the following (in simplified Go!!):

```
func FromProvenance(provenance *ValidatedProvenance) (ProvenanceIR) {
  bt := provenance.BuildType() // all valid provenances must have a buildType
  switch(bt) {
      case AMBER: return FromAmber(provenance)
      case SLSA02: return FromSLSA02(provenance)
      case SLSA1: // TODO
  }
}
```
Does that answer your question?

**Comment by mariaschett** [comment]
re: 1. sounds good!

re: 2. sounds good, too!

**Comment by mariaschett** [comment]
Ah, I just remembered re: 1. Binary Name: to generalize the endorser to work on ProvenanceIR---also for checking consistency---we either need to
- not check consistency on provenanceIR, but on a specific format,
- not demand a binary name to be present when checking consistency,
- give a binary name for every provenance format.
Any preference?

**Comment by rbehjati** [comment]
The binaryName is part of the generic intoto.Statement, and not specific to any of the formats. So this check can be done before converting provenances to `ProvenanceIR`, as is already done in `verifyConsistency`. But it should be fine to do this check after conversion to `ProvenanceIR` too, if you prefer that.
