### ISSUE TITLE
Add `ValidatedReferenceValues` and `ValidatedProvenanceValues` 

### ISSUE THREAD

**Issue by mariaschett** [project-oak/transparent-release#166]
The `ProvenanceIR` is essentially a dictionary between reference values and values from all possible provenance formats/versions.

However, depending on whether we are using the `ProvenanceIR` for reference values or values from the provenance format we have different invariants:
- For reference values we want at least one reference value for every value we want to verify to be present. The values we want to verify depend on the provenance format, which the caller needs to specify when validating reference values.
- For values from provenances we have at most one value for every value we want to verify. We allow 0 values, so we can map every possible provenance format to the `ProvenanceIR`.

I want to add two type aliases for `ProvenanceIR`: `ValidatedReferenceValues` and `ValidatedProvenanceValues` to signal these invariants.

Our `ProvenanceIRVerifier` currently verifies every _non-empty_ value in `ValidatedReferenceValue`.

If we impose the following conventions on `ValidatedReferenceValues`, we can use the same `ProvenanceIRVerifier` for every provenance format:

When validating the reference values, depending on the provenance format, we can additionally encode
- whether no value needs to be present (by setting the value to []). This allows to share the same reference values among different provenance formats and we can always add more reference values.
- whether any value at all should be present (by adding a default value).

Alternatively, we could  
- maintain a map from the struct fields of `ProvenanceIR` to bool to indicate whether they need to be verified for a given provenance format, but I don't see much benefit there,
- replace the generic `ProvenanceIRVerifier` by verifiers for every provenance format (e.g. `AmberProveanceVerifier`) calling the individual verification functions one by one, e.g., `verifyBinarySHA256Digest`, `verifyHasBuildCmd`. I think this has a lot of repetition.

**Comment by mariaschett** [comment]
@rbehjati WDYT?

**Comment by rbehjati** [comment]
Thanks for writing this down @mariaschett :)

I think it is a very good idea to have a single verifier that can handle all provenance formats. 

> When validating the reference values, depending on the provenance format, we can additionally encode

I am a bit confused about validate vs verify here. When you say `validating the reference values` do you mean when parsing the reference values into an instance of `ValidatedReferenceValues`? Ideally this should happen independent of the provenance and its format. I think this kind of logic and the interpretation of the reference values should happen in `ProvenanceIRVerifier` where we have both `ValidatedReferenceValues` and `ValidatedProvenanceValues`. 

On the topic of types, I think it is better to have separate types for provenances and reference values, as they are conceptually different things. I don't think type aliasing provides that level of distinction between the types, and I am not sure if type aliasing could enforce the invariants. But it can be good step towards clarifying the distinction between these two types.

**Comment by mariaschett** [comment]
> I am a bit confused about validate vs verify here. When you say `validating the reference values` do you mean when parsing the reference values into an instance of `ValidatedReferenceValues`

Validate would be the step after parsing. We would validate the reference values with respect to a provenace format to check whether the reference values contain all values which are needed for verifying this provenance format. This saves us these checks later on.

> type aliasing
It wouldn't enforce the invariants. We could do that by a wrapper, e.g.:

```golang
type ValidatedReferenceValues struct {
     Values ProvenanceIR
}
```

Happy to do that if we decide to go with the approach.

**Comment by rbehjati** [comment]
> Validate would check the parsed reference with respect to a provenace format to validate whether the reference values contain all values which are needed for verifying this provenance format. This also saves us these checks later on.

I think it would help to describe the validation and verification steps at a high level. My understanding from your description is that a single reference value file could be valid or invalid depending on which provenance format we want to verify. From the user's perspective that could be confusing. 

Instead of reporting to the user that the reference values are invalid, I'd rather report that the provenance is invalid, or inconsistent with the reference values. 

But I am also happy to proceed with your version and reevaluate the design once we have something more concrete :)

> Happy to do that if we decide to go with the approach.

With `ValidatedReferenceValues` as a wrapper around `ProvenanceIR` the two types would still be tightly entangled. I don't see much gain in that.

**Comment by mariaschett** [comment]
> My understanding from your description is that a single reference value file could be valid or invalid depending on which provenance format we want to verify. 

But that's true, no? 

Reference values can be sufficient for verifying one provenance format but not the other. E.g., if there are no reference values for `trusted-builder-digest` we can still verify a SLSA v02 provenance.

> be tightly entangled

Haha, but I want them to be tightly entangled! That way I always know which value and reference value belong together.

**Comment by rbehjati** [comment]
> But that's true, no?

We discussed this today, but I'll share it here as well :) In my opinion, the validity of the reference values should be independent of the provenance format. 

> Reference values can be sufficient for verifying one provenance format but not the other. E.g., if there are no reference values for `trusted-builder-digest` we can still verify a SLSA v02 provenance.

Yes, and we can also verify other formats that contain the `builder-image` even without a reference value for it. We just don't impose any requirements on the value, or the presence or absence of the `builder-image` value. It is the job of the provider of the reference values to make sure they have included all the important values. 

> Haha, but I want them to be tightly entangled! That way I always know which value and reference value belong together.

I would optimize the design for the expressiveness of the reference values, and a simpler verification logic. I think that can be more easily achieved if we have separate types for things that are conceptually different, come from different sources, and have different requirements. But if you think using a single type is a better design please go ahead with it :)

**Comment by mariaschett** [comment]
> separate types 

To sketch this seperation out. We would have two types:

```
type ProvenanceValues struct {
	BinarySHA256Digest string
	BuildCmd          []string
}
```

and

```
type ReferenceValue struct {
	BinarySHA256Digests []string
	BuildCmds           [][]string
}
```

With this seperation: when we want to compare a <Field> from the provenance values `Got` to the reference values `Want`, we need to "guess" the connection between `Want.BuildCmds` and `Got.BuildCmd`. 

I don't see the benefit of breaking this connection, _if_ the reference values are the same type as the provenance values. 

But maybe this assumption is wrong? 

If so, I agree, we should seperate `ProvenanceValues` and `ReferenceValues`.

(I understand this to be the case currently for `BuildCmds` as we just want to check whether there is any build command, but not which one. However, I thought of this as a not very common case.)

Just for completeness I add the following objectives:
-  Every field in the `ProvenanceValues` is optional (so we can map provenances of every build type to it). We can rely on default values, but I'd prefer to have some kind of `Option`. To achieve this in `ProvenanceValues` above we can use slices. Then types of the fields of the two structs are exactly the same.
-  We want to every function to verify a field to have the signature `(*ProvenanceValues) Verify<Field>(referenceValue ReferenceValue) : VerificationResult`. The alternative is to expose the underlying type of <Field>, e.g., string. We'd be loosing some type safety in this case.

> provider of the reference values to make sure they have included all the important values

I think that is a bit scary for the provider. Would we really be happy with all the reference values being optional? What do we do if the provider does not specify `BinarySHA256Digests`?

**Comment by mariaschett** [comment]
Great, as discussed: 
- I will seperate `ReferenceValues` from the `ProvenanceIR`.
- I will validate the provenance values into `ValidatedProvenanceIR` which (i) have exactly one binary digest, and (ii) either one or no value for every other field.
- We will rename to clarify that we always verify against the given reference values. In particular, we _can_ verify e.g., an Amber Provenance without checking all the Amber Provenance fields.  That means, if the reference values do not include reference values e.g., for builder digest, the verification does not check the builder digest in the given provenance. We will print a warning: "Did not verify builder digest", but will not fail. This is makes it more flexible for the user.
- We will add buildType as field to `ProvenanceIR`.

**Comment by rbehjati** [comment]
Great. Thanks :)

**Comment by rbehjati** [comment]
@mariaschett  can this be closed?

**Comment by mariaschett** [comment]
Yes, thank you!
