### ISSUE TITLE
Comparison to the in-toto CLI

### ISSUE THREAD

**Issue by jul-sh** [project-oak/transparent-release#17]
@rbehjati suggested tracking this is an issue, to be able to discuss it more here. :) 

Basically in-toto has it's own CLI, that is distinct (but adjacent to the in-toto attestation format). https://github.com/in-toto/in-toto. It looks very similar to our CLI, stating that is it used to: "Create layout, run supply chain steps and verify final product".

**Comment by jul-sh** [comment]
Some relevant details from their README



> ##### in-toto-run `in-toto-run` is used to execute a step in the software supply chain. This can be anything relevant to the project
> such as tagging a release with `git`, running a test, or building a
> binary. The relevant step name and command are passed as arguments,
> along with materials, which are files required for that step's command
> to execute, and products which are files expected as a result of the
> execution of that command. These, and other relevant details
> pertaining to the step are stored in a link file, which is signed
> using the functionary's key.
> 
> If materials are not passed to the command, the link file generated
> just doesn't record them. Similarly, if the execution of a command via
> `in-toto-run` doesn't result in any products, they're not recorded in
> the link file. Any files that are modified or used in any way during
> the execution of the command are not recorded in the link file unless
> explicitly passed as artifacts. Conversely, any materials or products
> passed to the command are recorded in the link file even if they're
> not part of the execution of the command.
> 
> See [this simple usage example from the demo application for more
> details](https://github.com/in-toto/demo). For a detailed list of all
> the command line arguments, run `in-toto-run --help` or look at the
> [online
> documentation](https://in-toto.readthedocs.io/en/latest/command-line-tools/in-toto-run.html).
> 
> ##### in-toto-record `in-toto-record` works similar to `in-toto-run` but can be used for multi-part software supply chain steps, i.e. steps
> that are not carried out by a single command. Use `in-toto-record
> start ...` to create a preliminary link file that only records the
> *materials*, then run the commands of that step or edit files manually and finally use `in-toto-record stop ...` to record the *products* and
> generate the actual link metadata file. For a detailed list of all
> command line arguments and their usage, run `in-toto-record start
> --help` or `in-toto-record stop --help`, or look at the [online documentation](https://in-toto.readthedocs.io/en/latest/command-line-tools/in-toto-record.html).
> 
> #### Release final product
> 
> In order to verify the final product with in-toto, the verifier must
> have access to the layout, the `*.link` files, and the project owner's
> public key(s).
> 
> #### Verification Use `in-toto-verify` on the final product to verify that
> - the layout was signed with the project owner's private key(s),
> - has not expired,
> - each step was performed and signed by the authorized functionary,
> - the functionaries used the commands, they were supposed to use,
> - materials and products of each step were in place as defined by the rules, and
> - run the defined inspections
> 
> For a detailed list of all command line arguments and their usage, run
> `in-toto-verify --help` or look at the [online
> documentation](https://in-toto.readthedocs.io/en/latest/command-line-tools/in-toto-verify.html).

**Comment by rbehjati** [comment]
The CLI seems to be work mostly with [in-toto layouts](https://github.com/in-toto/docs/blob/master/in-toto-spec.md#43-file-formats-layout). I have not looked at the full spec yet, but I don't see immediately how this relates to in-toto attestation, and in particular SLSA provenance. I feel like it should be possible to generate SLSA provenances from the layouts, but it does not seem like the CLI supports that.

**Comment by jul-sh** [comment]
Yeah, that bit was somewhat confusing to me as well. At first sight it seems there's a lot of overlap between in-toto layouts and SLSA. 

It's worth mentioning that the in-toto attestation readme mentions that attestations are meant to eventually be parsed by their CLI:

> This repository defines the in-toto  **attestation**  format, which
> represents authenticated metadata about a set of software artifacts.
> Attestations are intended for consumption by automated policy engines,
> such as  [in-toto](https://in-toto.io/)  and  [Binary
> Authorization](https://cloud.google.com/binary-authorization).
> 
> ## [](https://github.com/in-toto/attestation#important)IMPORTANT
> 
> This format is still in development and is not yet used by in-toto
> (see  [ITE-6](https://github.com/in-toto/ITE/blob/master/ITE/6/)).
> Versions 0.x are unstable and are subject to change until 1.0. Use git
> tags to switch between versions.
> 
> Latest stable version: 
> [0.1.0](https://github.com/in-toto/attestation/tree/v0.1.0)

If I had to guess I would speculate that in-toto layouts might be a temporary standard that they intend to replace later with attestations/SLSA.

**Comment by jul-sh** [comment]
Looks like ITE-6 (linked in the attestation readme) outlines their plan wrt this: https://github.com/in-toto/ITE/tree/master/ITE/6
