### ISSUE TITLE
Exposing the verify functionality

### ISSUE THREAD

**Issue by jul-sh** [project-oak/transparent-release#19]
The code needed to parse and verify SLSA files exists, but the functionality is not yet accessible from the command-line.

Regardless of the high level approach wrt to SLSA, TOML etc, I definitely need that functionality for the plan of using this tool outlined in: https://github.com/project-oak/oak/pull/2519#issuecomment-1030234644 

How should we move forward with this? :) cc @rbehjati @tiziano88

**Comment by rbehjati** [comment]
This is left as a TODO [in the README](https://github.com/project-oak/transparent-release/blob/main/README.md#verifying-provenances).

The idea is that `verify` is a library that can be used by anyone in any `go` project. Adding a command line tool **on top of it** sounds fine to me.

**Comment by jul-sh** [comment]
I'm glad that that is acceptable. How would propose going about doing that? I'm aware it's a TODO down the road atm. It is also blocking functional requirement for https://github.com/project-oak/oak/pull/2519#issuecomment-1030234644, so we'll it sooner for that

**Comment by rbehjati** [comment]
I think we just need a simple CLI tool in `cmd/verify/` similar to `cmd/build/main.go`. 

The verify tool will take a SLSA provenance file, so I think the CLI can be added right after merging #16. Right?

**Comment by jul-sh** [comment]
That would be possible, yes :)
