### ISSUE TITLE
Refactor `slsa` package

### ISSUE THREAD

**Issue by rbehjati** [project-oak/transparent-release#23]
@jul-sh Following your suggestion in https://github.com/project-oak/transparent-release/pull/21#pullrequestreview-877325031, I've added this test. I am not sure if this is the right place for the test though. 

I think we could rename the `slsa` package to `amber`, and have separate go files in it for provenance and endorsement, and their corresponding tests. WDYT?

_Originally posted by @rbehjati in https://github.com/project-oak/transparent-release/issues/22#issuecomment-1034856413_

**Comment by jul-sh** [comment]
Works for me, I'm not very opinionated about the module structure. :)
