### ISSUE TITLE
Explicity start and end validity fields in validityPeriod

### ISSUE THREAD

**Issue by tiziano88** [project-oak/transparent-release#30]
https://github.com/project-oak/transparent-release/blob/4c5e62a0ccb01d8407335d2514dfb8835d936360/schema/amber-endorsement/v1/predicate.json#L8-L21

The `releaseTime` field seems specific to releases, but the validityPeriod object may well be used for arbitrary time-bounded trusted files, so I think the name is too specific. Also the time of a release may not correspond to the time where it should be trusted. e.g. a release may be made today, but it can only be trusted in the future (e.g. to leave time for reviewers to inspect it).

Additionally, I think we should always require the expiry time; the author of this object may use a time far in the future if necessary.

Finally ,I think it may be useful to use terminology from existing systems, like x509 certs, in which such fields are called NotBefore / NotAfter (see https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.notbefore?view=net-6.0)

**Comment by rbehjati** [comment]
See also https://github.com/project-oak/transparent-release/pull/130#discussion_r978663313.

**Comment by rbehjati** [comment]
@tiziano88

I am thinking of changing the format and replacing `metadata` with a `validity` object as you suggested. The validity object will have `notBefore` and `notAfter` fields similar to [the X509 standard](https://www.ietf.org/rfc/rfc2459.txt). The `issuedOn` field will remain a separate timestamp, either as a field in `Issuer` or as a top-level field (if we decide to remove issuer, see #134). What do you think about this design?

Also, how much conformance to X509 do we need? In particular:

**Granularity of the time fields in the validity object:** In X509, the validity object specifies two dates. In in-toto, which is the standard that we are following, timestamps ([rfc3339](https://www.rfc-editor.org/rfc/rfc3339)) are used. Do we need `notBefore` and `notAfter` to be dates or timestamps? (I think `issuedOn` will have to remain a timestamp any way.)

**Encoding format of the time**: The X509 standard states the following on the validity dates: 
> "CAs conforming to this profile MUST always encode certificate validity dates through the year 2049 as UTCTime; certificate validity dates in 2050 or later MUST be encoded as GeneralizedTime."

Should we use these formats, which are standard ASN.1 types, or continue with [rfc3339](https://www.rfc-editor.org/rfc/rfc3339)?

I am leaning towards conforming to in-toto for the format, but for the granularity of the time in the `validity` object, I think date is good enough. 

cc @conradgrobler: What do you think?

**Comment by conradgrobler** [comment]
I agree that dates are fine for the notBefore and notAfter.

My understanding is that the endorsements will be published as JSON files. In that case I think representing the date as an rfc3339-formatted string is fine. Trying to add support for ASN.1 types will only complicate things unless the entire endorsement is converted to being ASN.1 encoded, which I would not think is a good idea.

**Comment by rbehjati** [comment]
Thanks Conrad. That is a good point, yes, claims and endorsements are encoded as JSON.

**Comment by tiziano88** [comment]
**Granularity of the time fields in the validity object**

I think we should stick to timestamps, and not give the impression that these are calendar dates, which will be confusing (e.g. what does it mean for something to expire on a given calendar date? that depends on timezone)

**Encoding format of the time**

I don't have a strong opinion; I think it makes sense to stick to format similar to what is already used in in-toto ([rfc3339](https://www.rfc-editor.org/rfc/rfc3339)), we don't need to emulate x.509 in terms of exact format, just semantics.
