### ISSUE TITLE
Use Standard Package Layout for Auth Logic Subdirectory.

### ISSUE THREAD

**Issue by aferr** [project-oak/transparent-release#53]
It should be more like this: https://github.com/golang-standards/project-layout

**Comment by aferr** [comment]
cc @rbehjati

**Comment by rbehjati** [comment]
Actually, I just noticed that after merging #46 `golint` fails with `2022/04/08 09:22:04 found packages authlogic (auth_logic_interface.go) and main (main.go) in experimental/auth-logic`.  This seems to completely disable `golint`. 

Could you please fix it? 
I'll update the linting script.

**Comment by aferr** [comment]
Yes the fix for that is in https://github.com/project-oak/transparent-release/pull/55
