### ISSUE TITLE
Restore Working Directory in FetchSourcesFromRepo and Verify

### ISSUE THREAD

**Issue by aferr** [project-oak/transparent-release#60]
cc: @rbehjati 

The current implementations of `FetchSourcesFromRepo` in `common/common.go` and `Verify` in `verify/verify.go` change the working directory but do not restore the working directory to whatever it was before they ran. This could cause issues if these functions are used by callers that expect the working directory not to change. These functions might be more predictable if they are either implemented in a way that does not change the working directory or: save the working directory at the beginning of the call to a temporary variable, change the directory as needed, and then change it back to whatever was stored in the temporary variable.

**Comment by rbehjati** [comment]
I agree. These functions should restore the working directory before returning. Feel free to assign the task to yourself if you plan to fix it :)

**Comment by tiziano88** [comment]
Or, better, can we make them not depend on PWD in the first place?

**Comment by rbehjati** [comment]
That is good idea, but I think it also makes sense for the functions not to have such side-effects. 

@aferr Do you know which callers currently rely on the working directory?
