### ISSUE TITLE
Remove bazel and convert the repo to a standard go project

### ISSUE THREAD

**Issue by rbehjati** [project-oak/transparent-release#67]
We now have `go.mod` and `go.sum`, and can use most `go` commands, e.g., for building. Can we now remove all bazel-related files and convert this repo to a standard project? 

Currently when running `go test ./...` some `auth-logic` tests fail. I think this is because of the genrules that fetch and build the dependencies. Is it possible to replaces those bazel targets with go commands? (`go generate ./...` might be relevant).

WDYT? @aferr @tiziano88

**Comment by tiziano88** [comment]
I think the only question is whether we expect to build / run this from google3, but at this point I don't think we are planning to do that, right? So I think we should go ahead

**Comment by rbehjati** [comment]
We do want to be able to use this as a third-party dependency for some tooling on Google3, but then it is just the same as any third-party project that we use on Google3. My understanding, based on a few projects I've seen on Google3, is that we can add the required BUILD files when synching to Google3.

**Comment by tiziano88** [comment]
So you are saying that github will be the source of truth, and it will be one-way synced to google3, and the BUILD files will be added there, right?

**Comment by rbehjati** [comment]
Yes. Exactly.

**Comment by rbehjati** [comment]
> Is there a way to fetch binaries from the go build system? I have never used go's build system.

Yes. That is my question too. I expect it to be possible. If not, we could perhaps write custom code to fetch the dependencies.

**Comment by tiziano88** [comment]
I don't think it will be possible in Go itself, but I think that would be part of the Docker image anyways, right? Similar to what we do in Oak, for instance. But I'm not sure it works for all the use cases.

**Comment by rbehjati** [comment]
Now that the authorization logic dependency is removed, I think we should go ahead and remove the use of bazel. 

The recent import to Google3 also proved that the use of bazel is not required. In fact, with gazelle a go project can be automatically converted into a bazel project.
