### ISSUE TITLE
Write Wrappers for at least 2 "Trusted Builders"

### ISSUE THREAD

**Issue by aferr** [project-oak/transparent-release#93]
Examples of two "trusted builders" are:
 - "Github Actions"
 - "Google Cloud Build"

**Comment by rbehjati** [comment]
What do the wrappers do? I thought they only verify the signature and generate some authorization logic predicates/facts based on the results. Cannot we use a single wrapper for this functionality?

**Comment by aferr** [comment]
IDK but maybe the outputs from "Github Actions" and "Google Cloud Build" are different and so we need a wrapper for each one.

**Comment by rbehjati** [comment]
The difference is very small. Only the builder field in the provenance should be different, and the signing keys will be different too. So I think a parametric wrapper should be enough. But perhaps add a description of the wrappers' functionality, then we can decide if a single wrapper is enough or not.

**Comment by aferr** [comment]
OK I don't know enough about these two trusted builders yet, but at least in principle your point makes sense. I'll keep reading up on these things in the meanwhile.

**Comment by aferr** [comment]
When I wrote this issue I didn't understand that provenance files had builder IDs in them and that we just needed to extend the go code to read this field. This issue is essentially covered by #98 which is fixed, so this issue is also fixed.
