### ISSUE TITLE
Generate endorsement file if authorization logic query passes

### ISSUE THREAD

**Issue by aferr** [project-oak/transparent-release#95]
We need a way to generate an endorsement file with the right contents if an authorization logic policy query is true (or generate an error if it is not true). We will use this to check if a predicate in the policy for releasing an endorsement file can be proved (is true), and generate the endorsement file if so.

**Comment by rbehjati** [comment]
We already have internal tooling for this. Somewhere along the path, we will have to sync the repos.

**Comment by aferr** [comment]
You already have tooling that *runs a query using the authorization logic compiler*, and if it passes, generates an endorsement file? It's just not on github? Can you send me a pointer to this in the appropriate channel?

**Comment by rbehjati** [comment]
We have code that generates the endorsement file, no auth logic involved. The existing code is not on Github.

**Comment by rbehjati** [comment]
For more clarity: We already have some verification logic that runs before generating the endorsement file. The idea is to only replace the verification part with authorization logic, not the entire pipeline.

**Comment by aferr** [comment]
Ah OK got it that makes more sense :)

Sounds like it should be helpful.

If this work package otherwise makes sense, the way I'll order it is probably going to be:
 - I read up more on github actions and google cloud build to understand enough about how to interact with these
 - I write the auth logic policy(/policies) for pulling in this stuff
 - write the wrappers
 - do the issue we are commenting on.

So you should have time to sync the repos before I'll be able to make use of that.

**Comment by aferr** [comment]
Hey @rbehjati, I recall that you mentioned you planned to move some things around after the workshop submission. Was moving this verification logic from the internal code base to this github code base part of that?

**Comment by rbehjati** [comment]
No, it was not. And I did not get the time to make the other refactoring either.
